// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbrQ3DtOFf1mBDGasGjvzJNBB9rVQXWIQ',
    appId: '1:607478642065:web:ead15981d0c41acac15630',
    messagingSenderId: '607478642065',
    projectId: 'civic-lens-app',
    authDomain: 'civic-lens-app.firebaseapp.com',
    storageBucket: 'civic-lens-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUon1kt_6tHIFhdp-_SwM1UK_kG3u5ADA',
    appId: '1:607478642065:android:2e8309444e5878a6c15630',
    messagingSenderId: '607478642065',
    projectId: 'civic-lens-app',
    storageBucket: 'civic-lens-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdoLp46ME5SxRcG-Ctm-0Jj2zv4qEjtVg',
    appId: '1:607478642065:ios:d9d04a3bbd65419fc15630',
    messagingSenderId: '607478642065',
    projectId: 'civic-lens-app',
    storageBucket: 'civic-lens-app.firebasestorage.app',
    iosBundleId: 'com.example.civicLens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdoLp46ME5SxRcG-Ctm-0Jj2zv4qEjtVg',
    appId: '1:607478642065:ios:d9d04a3bbd65419fc15630',
    messagingSenderId: '607478642065',
    projectId: 'civic-lens-app',
    storageBucket: 'civic-lens-app.firebasestorage.app',
    iosBundleId: 'com.example.civicLens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbrQ3DtOFf1mBDGasGjvzJNBB9rVQXWIQ',
    appId: '1:607478642065:web:633fcdac6860e817c15630',
    messagingSenderId: '607478642065',
    projectId: 'civic-lens-app',
    authDomain: 'civic-lens-app.firebaseapp.com',
    storageBucket: 'civic-lens-app.firebasestorage.app',
  );
}
